image: node:20

stages:
  - verify
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

lint:
  stage: verify
  script:
    - npm run lint
    - npm run typecheck

test:
  stage: verify
  script:
    - npm run test

build:
  stage: build
  script:
    - npm run build
    - npm run size
  artifacts:
    paths:
      - dist/
    expire_in: 7 days
